name: nrf-ble
channels:
  - defaults
dependencies:
  - python=3.10
  - pip:
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - bleak==0.21.1
      - bless==0.2.6
      - frozenlist==1.4.1
      - idna==3.6
      - multidict==6.0.5
      - pyobjc-core==9.2
      - pyobjc-framework-cocoa==9.2
      - pyobjc-framework-corebluetooth==9.2
      - pyobjc-framework-libdispatch==9.2
      - typing-extensions==4.10.0
      - yarl==1.9.4